// Game data with proper URLs for all games
export const games = [
  // Playable games (built-in)
  {
    id: "tic-tac-toe",
    title: "Tic Tac Toe",
    description: "Classic game of X's and O's where you try to get three in a row",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Tic%20Tac%20Toe",
    url: "/games/tic-tac-toe/index.html",
    category: "board",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Tic%20Tac%20Toe%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Tic%20Tac%20Toe%20Screenshot%202",
    ],
  },
  {
    id: "snake",
    title: "Snake",
    description: "Classic snake game where you grow longer as you eat food",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Snake",
    url: "/games/snake/index.html",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Snake%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Snake%20Screenshot%202",
    ],
  },
  {
    id: "flappy-bird",
    title: "Flappy Bird",
    description: "Navigate a bird through pipes by tapping to flap its wings in this addictive arcade game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Flappy%20Bird",
    url: "/games/flappy-bird/index.html",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Flappy%20Bird%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Flappy%20Bird%20Screenshot%202",
    ],
  },
  {
    id: "tetris",
    title: "Tetris",
    description: "Arrange falling blocks to clear lines and score points",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Tetris",
    url: "/games/tetris/index.html",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Tetris%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Tetris%20Screenshot%202",
    ],
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Clear the board without detonating any mines",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Minesweeper",
    url: "/games/minesweeper/index.html",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Minesweeper%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Minesweeper%20Screenshot%202",
    ],
  },
  {
    id: "pacman",
    title: "Pac-Man",
    description: "Navigate the maze, eat dots and avoid ghosts in this classic arcade game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Pac-Man",
    url: "/games/pacman/index.html",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Pac-Man%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Pac-Man%20Screenshot%202",
    ],
  },
  {
    id: "memory-game",
    title: "Memory Game",
    description: "Test your memory by matching pairs of cards",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Memory%20Game",
    url: "/games/memory-game/index.html",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Memory%20Game%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Memory%20Game%20Screenshot%202",
    ],
  },
  {
    id: "connect-four",
    title: "Connect Four",
    description: "Drop discs to connect four in a row before your opponent",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Connect%20Four",
    url: "/games/connect-four/index.html",
    category: "board",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Connect%20Four%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Connect%20Four%20Screenshot%202",
    ],
  },
  {
    id: "wordle",
    title: "Wordle",
    description: "Guess the five-letter word in six tries with color-coded hints",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Wordle",
    url: "/games/wordle/index.html",
    category: "word",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Wordle%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Wordle%20Screenshot%202",
    ],
  },
  {
    id: "pong",
    title: "Pong",
    description: "Classic arcade game where you control a paddle to hit a ball back and forth",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Pong",
    url: "/games/pong/index.html",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Pong%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Pong%20Screenshot%202",
    ],
  },

  // External games with embedded versions
  {
    id: "2048",
    title: "2048",
    description: "Combine tiles to reach 2048",
    thumbnail: "/placeholder.svg?height=200&width=300&text=2048",
    url: "https://play2048.co/",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=2048%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=2048%20Screenshot%202",
    ],
  },
  {
    id: "doodlejump",
    title: "Doodle Jump",
    description: "Jump from platform to platform and see how high you can go",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Doodle%20Jump",
    url: "https://www.crazygames.com/game/doodle-jump",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Doodle%20Jump%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Doodle%20Jump%20Screenshot%202",
    ],
  },
  {
    id: "chess",
    title: "Chess",
    description: "Classic strategy board game for two players",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Chess",
    url: "https://www.chess.com/play/computer",
    category: "board",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Chess%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Chess%20Screenshot%202",
    ],
  },
  {
    id: "elastic-man",
    title: "Elastic Man",
    description: "Play with an elastic face that stretches and deforms in amusing ways",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Elastic%20Man",
    url: "https://www.crazygames.com/game/elastic-man",
    category: "casual",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Elastic%20Man%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Elastic%20Man%20Screenshot%202",
    ],
  },
  {
    id: "dumb-ways-to-die",
    title: "Dumb Ways To Die",
    description: "Based on the viral safety campaign, play mini-games to avoid hilariously tragic deaths",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Dumb%20Ways%20To%20Die",
    url: "https://www.crazygames.com/game/dumb-ways-to-die-original",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Dumb%20Ways%20To%20Die%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Dumb%20Ways%20To%20Die%20Screenshot%202",
    ],
  },
  {
    id: "hextris",
    title: "Hextris",
    description: "A fast-paced puzzle game based on rotating hexagons to match colors",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Hextris",
    url: "https://hextris.io/",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Hextris%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Hextris%20Screenshot%202",
    ],
  },
  {
    id: "doge-miner",
    title: "Doge Miner",
    description: "Mine Dogecoins and upgrade your equipment in this idle clicker game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Doge%20Miner",
    url: "https://dogeminer.se/",
    category: "idle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Doge%20Miner%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Doge%20Miner%20Screenshot%202",
    ],
  },
  {
    id: "ice-dodo",
    title: "Ice Dodo",
    description: "Guide a dodo bird through challenging ice levels with precise controls",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Ice%20Dodo",
    url: "https://www.crazygames.com/game/ice-dodo",
    category: "platformer",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Ice%20Dodo%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Ice%20Dodo%20Screenshot%202",
    ],
  },
  {
    id: "fireboy-watergirl-ice",
    title: "Fireboy Watergirl Ice",
    description: "Control both Fireboy and Watergirl simultaneously in this cooperative puzzle game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Fireboy%20Watergirl%20Ice",
    url: "https://www.crazygames.com/game/fireboy-and-water-girl-4-crystal-temple",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Fireboy%20Watergirl%20Ice%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Fireboy%20Watergirl%20Ice%20Screenshot%202",
    ],
  },
  {
    id: "among-us",
    title: "Among Us",
    description: "Find the impostor among your crewmates in this social deduction game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Among%20Us",
    url: "https://www.crazygames.com/game/among-us-single-player",
    category: "strategy",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Among%20Us%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Among%20Us%20Screenshot%202",
    ],
  },
  {
    id: "geometry-dash",
    title: "Geometry Dash",
    description: "Rhythm-based platformer with challenging levels and upbeat music",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Geometry%20Dash",
    url: "https://www.crazygames.com/game/geometry-dash-online",
    category: "platformer",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Geometry%20Dash%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Geometry%20Dash%20Screenshot%202",
    ],
  },
  {
    id: "madalin-stunt-cars-2",
    title: "Madalin Stunt Cars 2",
    description: "Perform incredible stunts with high-performance cars in this 3D driving game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Madalin%20Stunt%20Cars%202",
    url: "https://www.crazygames.com/game/madalin-stunt-cars-2",
    category: "racing",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Madalin%20Stunt%20Cars%202%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Madalin%20Stunt%20Cars%202%20Screenshot%202",
    ],
  },
  {
    id: "pokemon-firered",
    title: "Pokemon Firered",
    description: "Embark on a journey to become a Pokemon master in this classic RPG adventure",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Pokemon%20Firered",
    url: "https://www.retrogames.cc/gameboy-advance-games/pokemon-fire-red-version-v1-0.html",
    category: "rpg",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Pokemon%20Firered%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Pokemon%20Firered%20Screenshot%202",
    ],
  },
  {
    id: "tanuki-sunset",
    title: "Tanuki Sunset",
    description: "Skateboard downhill as a raccoon in this stylish longboarding game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Tanuki%20Sunset",
    url: "https://www.crazygames.com/game/tanuki-sunset",
    category: "sports",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Tanuki%20Sunset%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Tanuki%20Sunset%20Screenshot%202",
    ],
  },
  {
    id: "learn-to-fly-2",
    title: "Learn To Fly 2",
    description: "Help a penguin achieve his dream of flight by launching him as far as possible",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Learn%20To%20Fly%202",
    url: "https://www.crazygames.com/game/learn-to-fly-2",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Learn%20To%20Fly%202%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Learn%20To%20Fly%202%20Screenshot%202",
    ],
  },
  {
    id: "merge-fruits",
    title: "Merge Fruits",
    description: "Combine identical fruits to create larger ones in this addictive puzzle game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Merge%20Fruits",
    url: "https://www.crazygames.com/game/merge-fruits",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Merge%20Fruits%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Merge%20Fruits%20Screenshot%202",
    ],
  },
  {
    id: "idle-breakout",
    title: "Idle Breakout",
    description: "Break bricks automatically and upgrade your balls in this idle version of Breakout",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Idle%20Breakout",
    url: "https://www.crazygames.com/game/idle-breakout",
    category: "idle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Idle%20Breakout%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Idle%20Breakout%20Screenshot%202",
    ],
  },
  {
    id: "red-ball-4",
    title: "Red Ball 4",
    description: "Roll and jump your way through challenging levels as a red ball",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Red%20Ball%204",
    url: "https://www.crazygames.com/game/red-ball-4",
    category: "platformer",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Red%20Ball%204%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Red%20Ball%204%20Screenshot%202",
    ],
  },
  {
    id: "tabs",
    title: "Totally Accurate Battle Simulator",
    description: "Create hilarious battles with wobbly physics-based combat",
    thumbnail: "/placeholder.svg?height=200&width=300&text=TABS",
    url: "https://www.crazygames.com/game/totally-accurate-battle-simulator-tabs",
    category: "strategy",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=TABS%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=TABS%20Screenshot%202",
    ],
  },
  {
    id: "zombs-royale",
    title: "Zombs Royale",
    description: "Battle royale game where you fight to be the last player standing in a zombie apocalypse",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Zombs%20Royale",
    url: "https://zombsroyale.io/",
    category: "battle-royale",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Zombs%20Royale%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Zombs%20Royale%20Screenshot%202",
    ],
  },
  {
    id: "bitlife",
    title: "Bitlife",
    description: "Life simulator where you make choices that affect your virtual character from birth to death",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Bitlife",
    url: "https://www.crazygames.com/game/bitlife-life-simulator",
    category: "simulation",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Bitlife%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Bitlife%20Screenshot%202",
    ],
  },
  {
    id: "1v1lol",
    title: "1V1.LOL",
    description: "Build and shoot game where you battle opponents in 1v1 matches with building mechanics",
    thumbnail: "/placeholder.svg?height=200&width=300&text=1V1.LOL",
    url: "https://1v1.lol/",
    category: "shooter",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=1V1.LOL%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=1V1.LOL%20Screenshot%202",
    ],
  },
  {
    id: "basketball-stars",
    title: "Basketball Stars",
    description: "Fast-paced basketball game where you compete in 1v1 matches with unique characters",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Basketball%20Stars",
    url: "https://www.crazygames.com/game/basketball-stars",
    category: "sports",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Basketball%20Stars%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Basketball%20Stars%20Screenshot%202",
    ],
  },
  {
    id: "bob-the-robber",
    title: "Bob The Robber",
    description: "Stealth game where you play as a thief avoiding security systems to steal valuables",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Bob%20The%20Robber",
    url: "https://www.crazygames.com/game/bob-the-robber",
    category: "stealth",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Bob%20The%20Robber%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Bob%20The%20Robber%20Screenshot%202",
    ],
  },
  {
    id: "fireboy-watergirl-forest",
    title: "Fireboy Watergirl Forest",
    description:
      "Cooperative puzzle game where you control both Fireboy and Watergirl through forest temple challenges",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Fireboy%20Watergirl%20Forest",
    url: "https://www.crazygames.com/game/fireboy-and-water-girl-in-the-forest-temple",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Fireboy%20Watergirl%20Forest%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Fireboy%20Watergirl%20Forest%20Screenshot%202",
    ],
  },
  {
    id: "cookie-clicker",
    title: "Cookie Clicker",
    description: "Incremental game where you click to produce cookies and buy upgrades to produce more automatically",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Cookie%20Clicker",
    url: "https://orteil.dashnet.org/cookieclicker/",
    category: "idle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Cookie%20Clicker%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Cookie%20Clicker%20Screenshot%202",
    ],
  },
  {
    id: "duck-life-4",
    title: "Duck Life 4",
    description: "Train your duck in various skills to compete in races and tournaments",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Duck%20Life%204",
    url: "https://www.crazygames.com/game/duck-life-4",
    category: "simulation",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Duck%20Life%204%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Duck%20Life%204%20Screenshot%202",
    ],
  },
  {
    id: "crossy-road",
    title: "Crossy Road",
    description: "Endless arcade hopper where you guide characters across busy roads and hazardous terrain",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Crossy%20Road",
    url: "https://www.crazygames.com/game/crossy-road-online",
    category: "arcade",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Crossy%20Road%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Crossy%20Road%20Screenshot%202",
    ],
  },
  {
    id: "drift-boss",
    title: "Drift Boss",
    description: "Endless driving game where you drift around corners to achieve high scores",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Drift%20Boss",
    url: "https://www.crazygames.com/game/drift-boss",
    category: "racing",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Drift%20Boss%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Drift%20Boss%20Screenshot%202",
    ],
  },
  {
    id: "fnaf",
    title: "Five Nights at Freddy's",
    description: "Survive five nights as a security guard in a pizzeria with haunted animatronic characters",
    thumbnail: "/placeholder.svg?height=200&width=300&text=FNAF",
    url: "https://www.crazygames.com/game/five-nights-at-freddys",
    category: "horror",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=FNAF%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=FNAF%20Screenshot%202",
    ],
  },
  {
    id: "retro-bowl",
    title: "Retro Bowl",
    description: "Pixel art American football game with simple controls and deep team management",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Retro%20Bowl",
    url: "https://www.crazygames.com/game/retro-bowl",
    category: "sports",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Retro%20Bowl%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Retro%20Bowl%20Screenshot%202",
    ],
  },
  {
    id: "paper-io",
    title: "Paper.io",
    description: "Capture territory by creating loops in this multiplayer IO game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Paper.io",
    url: "https://paper-io.com/",
    category: "io",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Paper.io%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Paper.io%20Screenshot%202",
    ],
  },
  {
    id: "moto-x3m",
    title: "Moto X3M",
    description: "Race your motorcycle through challenging obstacle courses and perform stunts",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Moto%20X3M",
    url: "https://www.crazygames.com/game/moto-x3m",
    category: "racing",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Moto%20X3M%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Moto%20X3M%20Screenshot%202",
    ],
  },
  {
    id: "happy-wheels",
    title: "Happy Wheels",
    description: "Physics-based obstacle course game with ragdoll physics and gruesome outcomes",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Happy%20Wheels",
    url: "https://www.crazygames.com/game/happy-wheels",
    category: "physics",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Happy%20Wheels%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Happy%20Wheels%20Screenshot%202",
    ],
  },
  {
    id: "ovo",
    title: "OvO",
    description: "Precision platformer with simple controls but challenging level design",
    thumbnail: "/placeholder.svg?height=200&width=300&text=OvO",
    url: "https://www.crazygames.com/game/ovo",
    category: "platformer",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=OvO%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=OvO%20Screenshot%202",
    ],
  },
  {
    id: "rooftop-snipers",
    title: "Rooftop Snipers",
    description: "Physics-based 2-player shooting game where you knock your opponent off the roof",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Rooftop%20Snipers",
    url: "https://www.crazygames.com/game/rooftop-snipers",
    category: "shooter",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Rooftop%20Snipers%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Rooftop%20Snipers%20Screenshot%202",
    ],
  },
  {
    id: "getaway-shootout",
    title: "Getaway Shootout",
    description: "Race against other players while shooting and using power-ups to reach the escape vehicle first",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Getaway%20Shootout",
    url: "https://www.crazygames.com/game/getaway-shootout",
    category: "action",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Getaway%20Shootout%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Getaway%20Shootout%20Screenshot%202",
    ],
  },
  {
    id: "run3",
    title: "Run 3",
    description: "Run through a space tunnel, avoiding holes and obstacles in this endless runner",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Run%203",
    url: "https://www.crazygames.com/game/run-3",
    category: "runner",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Run%203%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Run%203%20Screenshot%202",
    ],
  },
  {
    id: "short-life",
    title: "Short Life",
    description: "Navigate dangerous obstacles while trying to keep your character alive in this gory physics game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Short%20Life",
    url: "https://www.crazygames.com/game/short-life",
    category: "physics",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Short%20Life%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Short%20Life%20Screenshot%202",
    ],
  },
  {
    id: "smash-karts",
    title: "Smash Karts",
    description: "Multiplayer kart racing game with weapons and power-ups to take out your opponents",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Smash%20Karts",
    url: "https://smashkarts.io/",
    category: "racing",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Smash%20Karts%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Smash%20Karts%20Screenshot%202",
    ],
  },
  {
    id: "vex-5",
    title: "Vex 5",
    description: "Navigate a stickman through challenging obstacle courses with precise platforming",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Vex%205",
    url: "https://www.crazygames.com/game/vex-5",
    category: "platformer",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Vex%205%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Vex%205%20Screenshot%202",
    ],
  },
  {
    id: "snow-rider-3d",
    title: "Snow Rider 3D",
    description: "Race down snowy slopes on a snowboard, performing tricks and avoiding obstacles",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Snow%20Rider%203D",
    url: "https://www.crazygames.com/game/snow-rider-3d",
    category: "sports",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Snow%20Rider%203D%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Snow%20Rider%203D%20Screenshot%202",
    ],
  },
  {
    id: "worlds-hardest-game",
    title: "World's Hardest Game",
    description: "Navigate through levels filled with obstacles in this notoriously difficult game",
    thumbnail: "/placeholder.svg?height=200&width=300&text=World's%20Hardest%20Game",
    url: "https://www.crazygames.com/game/worlds-hardest-game",
    category: "puzzle",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=World's%20Hardest%20Game%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=World's%20Hardest%20Game%20Screenshot%202",
    ],
  },
  {
    id: "slither",
    title: "Slither.io",
    description: "Grow your snake by consuming glowing orbs and defeating other players",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Slither.io",
    url: "https://slither.io/",
    category: "io",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Slither.io%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Slither.io%20Screenshot%202",
    ],
  },
  {
    id: "tunnel-rush",
    title: "Tunnel Rush",
    description: "Speed through a colorful 3D tunnel while avoiding obstacles",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Tunnel%20Rush",
    url: "https://www.crazygames.com/game/tunnel-rush",
    category: "runner",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Tunnel%20Rush%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Tunnel%20Rush%20Screenshot%202",
    ],
  },
  {
    id: "slope",
    title: "Slope",
    description: "Roll down an endless slope at high speed while avoiding obstacles",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Slope",
    url: "https://www.crazygames.com/game/slope",
    category: "runner",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Slope%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Slope%20Screenshot%202",
    ],
  },
  {
    id: "shell-shockers",
    title: "Shell Shockers",
    description: "First-person shooter where you play as an egg in various game modes",
    thumbnail: "/placeholder.svg?height=200&width=300&text=Shell%20Shockers",
    url: "https://shellshock.io/",
    category: "shooter",
    screenshots: [
      "/placeholder.svg?height=400&width=600&text=Shell%20Shockers%20Screenshot%201",
      "/placeholder.svg?height=400&width=600&text=Shell%20Shockers%20Screenshot%202",
    ],
  },
]

// Process the games to ensure they have all required fields
export const processedGames = games.map((game) => ({
  ...game,
  thumbnail: game.thumbnail || `/placeholder.svg?height=200&width=300&text=${encodeURIComponent(game.title)}`,
  screenshots: game.screenshots || [
    `/placeholder.svg?height=400&width=600&text=${encodeURIComponent(game.title)}%20Screenshot%201`,
    `/placeholder.svg?height=400&width=600&text=${encodeURIComponent(game.title)}%20Screenshot%202`,
  ],
}))
